name: CI/CD for Scientific Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change this if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure your dependencies are listed here

      - name: Run tests
        run: |
          pytest testcases  # Adjust the path if your tests are located elsewhere

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job runs only after the build job is successful
    if: github.ref == 'refs/heads/main'  # Only deploy on pushes to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          echo "Deploying to server..."  # Replace this with your deployment commands
